name = "cmp"
mode = "binary"

[binary]
path = "./target/x86_64-unknown-linux-gnu/release/server"
runtime = "debian"

[service]
internal_port = 3000
always_on = true

[resources]
vcpu = 1
memory_mb = 256
